name:                ConvertDuplicater
version:             0.1.0.0
github:              "ogata-k/ConvertDuplicater"
license:             BSD3
author:              "ogata"
maintainer:          "ogtkzk@yahoo.co.jp"
copyright:           "(c) ogata"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ogata-k/ConvertDuplicater#readme>

dependencies:
- base >= 4.7 && < 5
- JuicyPixels
- repa
- filepath
- time >= 1.9

library:
  source-dirs: src

executables:
  CnvDup:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ConvertDuplicater

tests:
  CnvDup-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ConvertDuplicater
